// Generated by scripts/inventory.sh from the image pins (ADR 0032); do not edit.
// Regenerate after changing an image pin; CI checks that it is current.

export const INVENTORY = [
  {
    "id": "postgresql",
    "image": "docker.io/library/postgres",
    "version": "18.6-alpine",
    "digest": "sha256:d8703cd7fba306b9fec9268ecedfa8a966846c053036a60e3635791957eb2f66"
  },
  {
    "id": "pgbouncer",
    "image": null,
    "version": null,
    "digest": null
  },
  {
    "id": "valkey",
    "image": "docker.io/valkey/valkey",
    "version": "9.1.2-alpine",
    "digest": "sha256:3b83b0b6a598bb390c8186a408a69949772f439548a81c5ea0ab7ccf102c248d"
  },
  {
    "id": "openbao",
    "image": "docker.io/openbao/openbao",
    "version": "2.7.1",
    "digest": "sha256:a36ea8c27f0dcff5757664ad080425f96d3b6b2f33db3e76c4e2d3112fb17005"
  },
  {
    "id": "garage",
    "image": "docker.io/dxflrs/garage",
    "version": "v2.4.1",
    "digest": "sha256:0d7c74fc8ca6fef68a5a941c0e7558c8b1e92ba3588fa7505400e1350456c796"
  },
  {
    "id": "nginx",
    "image": "docker.io/library/nginx",
    "version": "1.31.6-alpine",
    "digest": "sha256:0530961ff0592b58c10f767535cc0abdfccf9e389ff7cc90f87320c1bc7e8506"
  },
  {
    "id": "netbox",
    "image": "docker.io/netboxcommunity/netbox",
    "version": "v4.7.2-5.1.1",
    "digest": "sha256:5a651e29340570b69585a56224ef5023ed1c6339cee6c7028c336e35099291bc"
  },
  {
    "id": "node",
    "image": "docker.io/library/node",
    "version": "26.10.0-trixie-slim",
    "digest": "sha256:0e6e6feab3409d135561b2dac7f75dad902ceb5e14c35de4521155779ae70cee"
  },
  {
    "id": "restic",
    "image": "docker.io/restic/restic",
    "version": "0.19.1",
    "digest": "sha256:136600b6ff6843d61d355f7f71f460a166429f35de6fd11b568fece3c9a4d510"
  },
  {
    "id": "alpine",
    "image": "docker.io/library/alpine",
    "version": "3.24.2",
    "digest": "sha256:d56c381f961d307a21b3ca004cf1e3910f106644aefb1f43e654c8a56c4fd395"
  },
  {
    "id": "prometheus",
    "image": "docker.io/prom/prometheus",
    "version": "v3.15.0",
    "digest": "sha256:efd719c99d83b060d9daefdcf00360461adf279f45ef5391f8d111892118753e"
  },
  {
    "id": "loki",
    "image": "docker.io/grafana/loki",
    "version": "3.7.8",
    "digest": "sha256:1107dd5274e0ada47e42472b7a7e71f3b2a2fe878878108f3e2f9e51528f0193"
  },
  {
    "id": "grafana",
    "image": "docker.io/grafana/grafana",
    "version": "13.2.3",
    "digest": "sha256:b28bae15e219c998fb0e0424ed724930cc61b1f61fb404d47c862f9a23f9e572"
  },
  {
    "id": "alloy",
    "image": "docker.io/grafana/alloy",
    "version": "v1.20.1",
    "digest": "sha256:2aa2099af76c0098d4af7a4d6e48f86cb66dc1a000222ad927a1c67c6542d13f"
  },
  {
    "id": "node-exporter",
    "image": "quay.io/prometheus/node-exporter",
    "version": "v1.12.1",
    "digest": "sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0"
  },
  {
    "id": "blackbox-exporter",
    "image": "quay.io/prometheus/blackbox-exporter",
    "version": "v0.28.0",
    "digest": "sha256:e753ff9f3fc458d02cca5eddab5a77e1c175eee484a8925ac7d524f04366c2fc"
  },
  {
    "id": "postgres-exporter",
    "image": "quay.io/prometheuscommunity/postgres-exporter",
    "version": "v0.20.1",
    "digest": "sha256:ac5ec343104fae0e2d84a27bb8d69b38430a11910c5382cad85d478d2bab713e"
  },
  {
    "id": "pgbouncer-exporter",
    "image": "quay.io/prometheuscommunity/pgbouncer-exporter",
    "version": "v0.12.1",
    "digest": "sha256:30f31b6c2efdad3647f8182cc7c1a3a19e42bae5d17387694989f969371c230d"
  },
  {
    "id": "redis-exporter",
    "image": "docker.io/oliver006/redis_exporter",
    "version": "v1.93.0",
    "digest": "sha256:6ca518a72f30f7f576ef92963de1b91d3c3f5fd3aeac949f878bfda183587820"
  },
  {
    "id": "host",
    "image": null,
    "version": null,
    "digest": null
  }
]
