FROM docker.io/library/alpine:3.24.2@sha256:d56c381f961d307a21b3ca004cf1e3910f106644aefb1f43e654c8a56c4fd395
RUN apk add --no-cache openssl
COPY containers/certs/issue.sh /usr/local/bin/issue.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/issue.sh"]
